name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-n-release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run:
          sudo apt-get update && sudo apt-get install texlive-full make

      - name: Compile Document
        run:
          make

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_template: 'yyyy.mm.dd.i'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files:
            resume.pdf
