name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run:
          sudo apt-get update && sudo apt-get install texlive-full make

      - name: Compile Document
        run:
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: resume.pdf

  release:

    needs: [build]

    if: github.event_name == 'release' && github.event.action == 'published'

    steps:

      - uses: actions/download-artifact@v4
        with:
          name: CV

      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf


